project_id = "xexgdtlctyuycohzhmuu"

[auth]
enabled = true
site_url = "https://de39dd50-14fe-4ffc-975a-32dc85fa2af8.sandbox.lovable.dev"
additional_redirect_urls = ["https://localhost:8910"]

[functions.generate-inspecao-pdf]
verify_jwt = true

[functions.serve-hsa-report]
verify_jwt = false

[functions.serve-treinamento-file]
verify_jwt = false

[functions.serve-certificado]
verify_jwt = false