project_id = "xexgdtlctyuycohzhmuu"

[functions.serve-treinamento-file]
verify_jwt = false

[functions.enviar-notificacao-solicitacao]
verify_jwt = false

[functions.send-email-webhook]
verify_jwt = false