// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzadcuxubwraehpoohjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6YWRjdXh1YndyYWVocG9vaGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMDQ2ODksImV4cCI6MjA3NTY4MDY4OX0.QWkOf7JrageT5CKAbgItQZNSvdYJjkQISMSocE1T9ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});