
import { DesvioFormData } from "@/types/desvios";

export const getDefaultFormValues = (): DesvioFormData => ({
  data: "",
  hora: "",
  ano: "",
  mes: "",
  ccaId: "",
  tipoRegistro: "",
  processo: "",
  eventoIdentificado: "",
  causaProvavel: "",
  responsavelInspecao: "",
  empresa: "",
  disciplina: "",
  engenheiroResponsavel: "",
  descricao: "",
  baseLegal: "",
  supervisorResponsavel: "",
  encarregadoResponsavel: "",
  colaboradorInfrator: "",
  funcao: "",
  matricula: "",
  tratativaAplicada: "",
  responsavelAcao: "",
  prazoCorrecao: "",
  situacao: "",
  situacaoAcao: "",
  aplicacaoMedidaDisciplinar: false,
  exposicao: "",
  controle: "",
  deteccao: "",
  efeitoFalha: "",
  impacto: "",
  probabilidade: 0,
  severidade: 0,
  classificacaoRisco: "",
});
