// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlmtwqlegqcneuvfrgsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbXR3cWxlZ3FjbmV1dmZyZ3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDEyNzEsImV4cCI6MjA2NTY3NzI3MX0.VPtihaixQY_QDkjOw43_WfmkQVkBBKBWr1K4VBazcHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});